CREATE TABLE `INTERVIEW_QUESTION` (
	`INTER_NO`	VARCHAR(50)	NOT NULL,
	`QUESTION`	VARCHAR(200)	NOT NULL,
	`ANSWER`	TEXT	NOT NULL,
	`SOURCE`	VARCHAR(100)	NULL,
	`CREATED_AT`	DATETIME	NULL,
	`USER_NO`	VARCHAR(50)	NOT NULL,
	`APPLICAT_NO`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `RESUME` (
	`RESUME_NO`	VARCHAR(50)	NOT NULL,
	`TITLE`	VARCHAR(200)	NOT NULL,
	`CREATED_AT`	DATETIME	NULL,
	`UPDATED_AT`	DATETIME	NULL,
	`TYPE`	VARCHAR(100)	NULL,
	`USER_NO`	VARCHAR(50)	NOT NULL,
	`APPLICAT_NO`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `API_KEY` (
	`USER_ID`	VARCHAR(100)	NOT NULL,
	`OPENAI_KEY`	VARCHAR(200)	NOT NULL,
	`UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `USER` (
	`USER_NO`	VARCHAR(50)	NOT NULL,
	`PASSWORD`	VARCHAR(200)	NOT NULL,
	`NAME`	VARCHAR(100)	NOT NULL,
	`PHONE`	VARCHAR(50)	NULL,
	`EMAIL`	VARCHAR(100)	NULL,
	`CREATED_AT`	DATETIME	NULL,
	`USER_ID`	VARCHAR(100)	NOT NULL
);

CREATE TABLE `EDUCATION` (
	`EDU_NO`	VARCHAR(50)	NOT NULL,
	`TITLE`	VARCHAR(200)	NOT NULL,
	`MAJOR`	VARCHAR(100)	NULL,
	`SDATE`	DATE	NULL,
	`EDATE`	DATE	NULL,
	`STATE`	VARCHAR(100)	NULL	COMMENT '재학/졸업/휴학',
	`DEGREE`	VARCHAR(100)	NULL	COMMENT '학위/석사/박사',
	`USER_NO`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `RESUME_ITEM` (
	`RITEM_NO`	VARCHAR(50)	NOT NULL,
	`ORDER_NO`	INT	NULL,
	`QUESTION`	TEXT	NULL,
	`ANSWER`	TEXT	NULL,
	`CHAR_LIMIT`	INT	NULL,
	`RESUME_NO`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `CERTIFICATE` (
	`CER_NO`	VARCHAR(50)	NOT NULL,
	`TITLE`	VARCHAR(200)	NOT NULL,
	`SDATE`	DATE	NULL,
	`ISSUER`	VARCHAR(200)	NULL	COMMENT '재학/졸업/휴학',
	`USER_NO`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `CAREER` (
	`CAREER_NO`	VARCHAR(50)	NOT NULL,
	`TITLE`	VARCHAR(200)	NOT NULL,
	`SDATE`	DATE	NULL,
	`EDATE`	DATE	NULL,
	`POSITION`	VARCHAR(100)	NULL	COMMENT '재학/졸업/휴학',
	`DEPARTMENT`	VARCHAR(100)	NULL,
	`TASK`	VARCHAR(100)	NULL	COMMENT '학위/석사/박사',
	`REASON`	VARCHAR(200)	NULL,
	`USER_NO`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `APPLICATION` (
	`APPLICAT_NO`	VARCHAR(50)	NOT NULL,
	`JOB_TITLE`	VARCHAR(200)	NOT NULL,
	`COMPANY`	VARCHAR(100)	NOT NULL,
	`UPDATE_AT`	DATETIME	NULL,
	`SDATE`	DATETIME	NULL,
	`EDATE`	DATETIME	NULL,
	`STATE`	VARCHAR(100)	NULL,
	`MEMO`	TEXT	NULL,
	`INTERVIEW_DATE1`	DATETIME	NULL,
	`INTERVIEW_DATE2`	DATETIME	NULL,
	`USER_NO`	VARCHAR(50)	NOT NULL
);

ALTER TABLE `INTERVIEW_QUESTION` ADD CONSTRAINT `PK_INTERVIEW_QUESTION` PRIMARY KEY (
	`INTER_NO`
);

ALTER TABLE `RESUME` ADD CONSTRAINT `PK_RESUME` PRIMARY KEY (
	`RESUME_NO`
);

ALTER TABLE `API_KEY` ADD CONSTRAINT `PK_API_KEY` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`USER_NO`
);

ALTER TABLE `EDUCATION` ADD CONSTRAINT `PK_EDUCATION` PRIMARY KEY (
	`EDU_NO`
);

ALTER TABLE `RESUME_ITEM` ADD CONSTRAINT `PK_RESUME_ITEM` PRIMARY KEY (
	`RITEM_NO`
);

ALTER TABLE `CERTIFICATE` ADD CONSTRAINT `PK_CERTIFICATE` PRIMARY KEY (
	`CER_NO`
);

ALTER TABLE `CAREER` ADD CONSTRAINT `PK_CAREER` PRIMARY KEY (
	`CAREER_NO`
);

ALTER TABLE `APPLICATION` ADD CONSTRAINT `PK_APPLICATION` PRIMARY KEY (
	`APPLICAT_NO`
);

-- 1. USER 테이블을 참조하는 테이블들
ALTER TABLE `APPLICATION` ADD CONSTRAINT `FK_USER_TO_APPLICATION` 
    FOREIGN KEY (`USER_NO`) REFERENCES `USER` (`USER_NO`);

ALTER TABLE `RESUME` ADD CONSTRAINT `FK_USER_TO_RESUME` 
    FOREIGN KEY (`USER_NO`) REFERENCES `USER` (`USER_NO`);

ALTER TABLE `INTERVIEW_QUESTION` ADD CONSTRAINT `FK_USER_TO_INTERVIEW` 
    FOREIGN KEY (`USER_NO`) REFERENCES `USER` (`USER_NO`);

ALTER TABLE `EDUCATION` ADD CONSTRAINT `FK_USER_TO_EDUCATION` 
    FOREIGN KEY (`USER_NO`) REFERENCES `USER` (`USER_NO`);

ALTER TABLE `CAREER` ADD CONSTRAINT `FK_USER_TO_CAREER` 
    FOREIGN KEY (`USER_NO`) REFERENCES `USER` (`USER_NO`);

ALTER TABLE `CERTIFICATE` ADD CONSTRAINT `FK_USER_TO_CERTIFICATE` 
    FOREIGN KEY (`USER_NO`) REFERENCES `USER` (`USER_NO`);

-- 2. APPLICATION(지원등록) 테이블을 참조하는 테이블들
ALTER TABLE `RESUME` ADD CONSTRAINT `FK_APP_TO_RESUME` 
    FOREIGN KEY (`APPLICAT_NO`) REFERENCES `APPLICATION` (`APPLICAT_NO`);

ALTER TABLE `INTERVIEW_QUESTION` ADD CONSTRAINT `FK_APP_TO_INTERVIEW` 
    FOREIGN KEY (`APPLICAT_NO`) REFERENCES `APPLICATION` (`APPLICAT_NO`);

-- 3. RESUME(자기소개서) 테이블을 참조하는 테이블
ALTER TABLE `RESUME_ITEM` ADD CONSTRAINT `FK_RESUME_TO_RITEM` 
    FOREIGN KEY (`RESUME_NO`) REFERENCES `RESUME` (`RESUME_NO`);





-- 쿼리문 삭제
-- 1단계: 가장 말단 자식들 삭제
DROP TABLE IF EXISTS `RESUME_ITEM`;
DROP TABLE IF EXISTS `INTERVIEW_QUESTION`;

-- 2단계: 중간 관계 테이블 삭제
DROP TABLE IF EXISTS `RESUME`;
DROP TABLE IF EXISTS `EDUCATION`;
DROP TABLE IF EXISTS `CERTIFICATE`;
DROP TABLE IF EXISTS `CAREER`;
DROP TABLE IF EXISTS `APPLICATION`;

-- 3단계: 최상위 부모 및 독립 테이블 삭제
DROP TABLE IF EXISTS `USER`;
DROP TABLE IF EXISTS `API_KEY`;